base14:
	python3 lec14base.py

timer:
	python3 mytimer.py

v11:
	python3 count.the.v11.py data.v1

v10:
	python3 count.the.v10.py data.v1

v9:
	python3 count.the.v09.py data.v1

v12:
	python3 count.the.v12.py data.v1

p8:
	python3 count.the.p8.py < data.v1

push:
	git commit -a
	git push
