# Comment
l03p02:
	python3 lec04p02.py

l03p01:
	python3 lec04p01.py

lec04:
	python3 lec04base.py

lec03::
	python3 lec03base.py

origl03p02:
	python3 count.new.version.1.py
#	Same as this, due to symbolic link
#	python3 lec03.p02.py

push:
	git commit -a
	git push
